name: Test

on:
  push:
    branches:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Validate wrapper
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build
        run: mvn --batch-mode --update-snapshots verify
